interface Cell {
  safe?: boolean;
  break?: string;
  start?: string;
}

export const cells: Cell[] = [
  { safe: false },
  { safe: true, start: "yellow", break: "hor" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: true, start: "red", break: "hor" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: true, start: "blue", break: "hor" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: true, start: "green", break: "hor" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false },
  { safe: false, break: "hor" },
];
