interface Cell {
  safe?: boolean;
  break?: string;
  start?: string;
}

export const cells: Cell[] = [
  { safe: false, break: "ver" },
  { safe: true, start: "yellow" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "str" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: true, start: "red" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "str" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: true, start: "blue" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "str" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: false, break: "ver" },
  { safe: true, start: "green" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: false, break: "str" },
  { safe: false },
  { safe: false },
  { safe: false },
  { safe: true },
  { safe: false },
  { safe: false, break: "hor" },
  { safe: false },
  { safe: false },
];
